"""Phase 1 gold-set acceptance: counts, schema, internal consistency."""

import pytest

from evals.goldset import loader
from evals.judge import rubrics

pytestmark = pytest.mark.smoke


def test_discrimination_counts():
    items = loader.discrimination()
    labels = {i.label for i in items}
    assert {"genuine", "spurious", "paraphrase"} <= labels
    n_genuine = sum(1 for i in items if i.label == "genuine")
    # Real (corpus-derived) items available without any model endpoint.
    # The plan's >=150 target is reached once the three imitation tiers are
    # generated by evals/goldset/gen_imitations.py (needs an open-weights
    # endpoint); that also adds the "imitation" label. See below.
    assert len(items) >= 140
    assert n_genuine >= 100
    imitations = [i for i in items if i.label == "imitation"]
    if imitations:
        assert len(items) >= 150
        assert {i.tier for i in imitations} == {"low", "medium", "high"}


def test_structural_counts_and_schema():
    items = loader.structural()
    assert len(items) >= 60
    ids = [i.id for i in items]
    assert len(ids) == len(set(ids))
    moves = (
        "identity-through-change",
        "unity-of-opposites",
        "process-primacy",
        "measure-and-exchange",
        "tension-as-structure",
        "perspectival-opposition",
    )
    for it in items:
        assert 3 <= len(it.checks) <= 5, it.id
        assert it.strong.strip() and it.kitsch.strip(), it.id
        assert it.strong != it.kitsch, it.id
        # at least one check keyed to a named move
        assert any(any(m in c.lower() for m in moves) for c in it.checks), it.id


def test_structural_domain_diversity():
    domains = {i.domain for i in loader.structural()}
    assert len(domains) >= 7  # plan lists 7 target domains


def test_tension_counts_and_labels():
    items = loader.tension()
    # >=40 labeled dialogues: each item yields a hold track + a collapse track.
    assert 2 * len(items) >= 40
    for it in items:
        assert len(it.user_turns) == len(it.hold_track) == len(it.collapse_track), it.id
        assert 1 <= it.collapse_turn <= len(it.user_turns), it.id
        assert it.collapse_mode in ("one_side", "vague", "evade"), it.id
        # dialogue interleaving is well-formed
        d = it.as_dialogue("hold")
        assert [t["role"] for t in d[:2]] == ["user", "assistant"]


def test_compression_counts_and_tripwire():
    items = loader.compression()
    assert len(items) >= 20
    tripwires = [i for i in items if i.kind == "tripwire"]
    distractors = [i for i in items if i.kind != "tripwire"]
    assert len(tripwires) >= 10
    assert len(distractors) >= 3  # guards against "always pick shorter"
    for it in items:
        assert it.correct in ("short", "long")
        if it.kind == "tripwire":
            assert it.correct == "short"
            assert len(it.short) < len(it.long)


def test_consistency_counts_and_balance():
    items = loader.consistency()
    assert len(items) >= 30
    compat = [i for i in items if i.label == "compatible"]
    incompat = [i for i in items if i.label == "incompatible"]
    assert len(compat) >= 10 and len(incompat) >= 10
    for it in incompat:
        assert it.violated in range(1, 7), it.id


def test_weights_sum_to_one():
    assert abs(sum(rubrics.WEIGHTS.values()) - 1.0) < 1e-9


def test_no_gold_text_empty():
    for s in loader.all_gold_text():
        assert s and s.strip()
